export const SET_PROFILE_ERRORS = "SET_PROFILE_ERRORS";
export const RESET_PROFILE_ERRORS = "RESET_PROFILE_ERRORS";
export const SET_PASSWORD_UPDATE_ERRORS = "SET_PASSWORD_UPDATE_ERRORS";
export const RESET_PASSWORD_UPDATE_ERRORS = "RESET_PASSWORD_UPDATE_ERRORS";
export const SET_ABOUT_UPDATE_ERRORS = "SET_PASSWORD_UPDATE_ERRORS";
export const RESET_ABOUT_UPDATE_ERRORS = "RESET_PASSWORD_UPDATE_ERRORS";
export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET";